site_name: GwToolbox Helper Plugins


repo_url: https://github.com/franneck94/GwToolbox_HelperPlugins
repo_name: franneck94/GwToolbox_HelperPlugins

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

nav:
  - "Index": index.md
  - "Chat": General/ChatCommands.md
  - "Hero": General/HeroWindow.md
  - "Hotkeys": General/Hotkeys.md
  - "UW EMO": Uw/Emo.md
  - "UW Mesmer": Uw/Mesmer.md
  - "UW Ranger": Uw/Ranger.md
  - "UW DB": Uw/Db.md
