name: Documentation

on:
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
